from colorama import Fore

print('\n\n')
print("          "+Fore.GREEN+"       ---             ")
print("             t          n          ")
print("         r                  x     ")
print("                             ")
print("      f          /\           labs ")
print("                /  \             ")
print("               /    \       ")
print("    |_________/______\__________|")
print("    |        /        \         |")
print("            /__________\                              __________________________________  ") 
print("                 |                                          "+Fore.WHITE+"| Luna Version 0.0.1"+Fore.GREEN)
print("                 |                                          "+Fore.WHITE+"| Creator: FRTNX"+Fore.GREEN)  
print("                 |                                          "+Fore.WHITE+"| Contact: frtnx@protonmail.com "+Fore.GREEN)
print("                 |")
print("                ---")
print("\n\n"+Fore.WHITE)